name: Github Actions

on: [push, pull_request]

jobs:
  host-x86:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        compiler: [gcc, clang]
        architecture: [arm, riscv]
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: build artifact
        env:
          CC: ${{ matrix.compiler }}
        run: |
          sudo apt-get update -q -y
          sudo apt-get install -q -y graphviz jq
          sudo apt-get install -q -y qemu-user
          sudo apt-get install -q -y build-essential
          make distclean config ARCH=${{ matrix.architecture }}
          make check-snapshot || exit 1
          make check || exit 1

  host-arm:
    runs-on: ubuntu-24.04
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: build artifact
      # The GitHub Action for non-x86 CPU
      # https://github.com/uraimo/run-on-arch-action
      uses: uraimo/run-on-arch-action@v3
      with:
        arch: armv7
        distro: ubuntu24.04
        githubToken: ${{ github.token }}
        install: |
          apt-get update -qq -y
          apt-get install -yqq build-essential
        run: |
          make config ARCH=arm
          make check || exit 1

  coding-style:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: coding convention
      run: |
            sudo apt-get install -q -y clang-format-18
            .ci/check-newline.sh
            .ci/check-format.sh
      shell: bash
